repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: name-tests-test
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-scss-lint
    rev: v0.59.0
    hooks:
    -   id: scss-lint
-   repo: https://github.com/pre-commit/mirrors-ruby-lint
    rev: v2.3.1-1
    hooks:
    -   id: ruby-lint
-   repo: https://github.com/pre-commit/mirrors-jshint
    rev: v2.13.4
    hooks:
    -   id: jshint
